package com.relx.naming;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Default Application entry point generated by Spring Initializer
 */
@SpringBootApplication
public class NamingApplication {

	public static void main(String[] args) {
		SpringApplication.run(NamingApplication.class, args);
	}

}
